enum networkCommands {
	test,
	client_connect,
	client_disconnect,
	receive_my_id,
	send_ping,
	send_username,
	update_username,
	get_all_clients,
	send_move_direction,
	update_clients,
	receive_ping_other,
	end_of_packet,
	update_client_serverSide,
}